spring:
  application:
    name: eureka-server-demo

server:
  port: ${PORT:8763}

eureka:
  instance:
    hostname: peer3
    metadata-map:
      zone: zone3
  client:
    service-url:
      default-zone: http:localhost:8761/eureka/,http://localhost:8762/eureka/