server:
  port: 8080

spring:
  application:
    name: gateway-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
#    register-with-eureka: false

zuul:
  prefix: /api
  routes:
    account-service:
      path: /account/**
    customer-service:
      path: /customer/**
    order-service:
      path: /order/**
    product-service:
      path: /product/**
