spring:
  application:
    name: account-service

logging:
  level:
    org.springframework.web.filter.commonsRequestLogginFilter: DEBUG

---
spring:
  profiles: zone1

eureka:
  instance:
    metadata-map:
      zone: zone1
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
      prefer-same-zone-eureka: true

server:
  port: 8091

---
spring:
  profiles: zone2

eureka:
  instance:
    metadata-map:
      zone: zone2
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
      prefer-same-zone-eureka: true

server:
  port: 9091