server:
  port: 8888
spring:
  application:
    name: config-server
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
