spring:
  application:
    name: eureka-client-demo


server:
  port: ${PORT:8083}
eureka:
  instance:
    metadata-map:
      zone: zone3
      preferSameZoneEureka: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
