spring:
  application:
    name: eureka-server-demo

server:
  port: ${PORT:8761}

eureka:
  instance:
    hostname: peer1
    metadata-map:
      zone: zone1
  client:
    service-url:
      default-zone: http:localhost:8762/eureka/,http://localhost:8763/eureka/
