spring:
  application:
    name: eureka-client-demo

server:
  port: ${PORT:8082}
eureka:
  instance:
    metadata-map:
      zone: zone2
      preferSameZoneEureka: true
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
